# Этот файл указывает Netlify, где находятся ваши серверные функции.
[functions]
  directory = "netlify/functions/"

# Этот раздел говорит Netlify, что для сайта не требуется команда сборки,
# и что публиковать нужно все файлы из корневой папки.
[build]
  command = "" # Команда сборки не нужна
  publish = "/" # Публикуем корень проекта
# Увеличиваем время ожидания для функции result до 30 секунд
[functions."result"]
  timeout = 30
