## Netlify configuration

[build]
  command = "echo 'No build command'"
  publish = "."
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

[functions."stripe-webhook"]
  # Stripe SDK is used in the webhook
  external_node_modules = ["stripe"]

[[headers]]
  for = "/.netlify/functions/stripe-webhook"
  [headers.values]
    Content-Type = "application/json"

